#Дефолты, применяются при пропуске ввода
defs_com: !!str 5
defs_baud: !!str 115200
defs_plcaddress: 30
#Шапка R7
R7title_bytecount:
  - 4
  - 1
  - 1
  - 4
  - 1
R7title_comment:
  - Номер архивной записи
  - Тип записи
  - Флаг последней записи
  - Время формирования архива
  - Порядковый номер ФБ архивации