name: Go build and release

on:
  push:
    tags: 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod
        cache-dependency-path: ./go.sum

    - name: Install Dependencies
      run: |
        go get .
    - name: Build
      run: |
        env GOOS=windows GOARCH=amd64 go build -v -o ArchReader.exe .
        env GOOS=linux GOARCH=amd64 go build -v -o ArchReader .
        zip -r ${{ github.event.repository.name }}-windows-amd64.zip ArchReader.exe config.yml
        tar -cvf ${{ github.event.repository.name }}-linux-amd64.tar ArchReader config.yml
        
    # - name: Test
    #   run: go test -v ./...

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ github.event.repository.name }}-windows-amd64.zip
          ${{ github.event.repository.name }}-linux-amd64.tar
